// Lightweight source registry — names and tiers only, no fetch functions.
// Import this from API functions that only need source metadata, not the full crawl.
const SOURCES = [
  // Tier 1 — APIs
  { name: 'Eventbrite',          tier: 1 },
  { name: 'Meetup',              tier: 1 },
  { name: 'Ticketmaster',        tier: 1 },
  { name: 'Songkick',            tier: 1 },
  { name: 'Bandsintown',         tier: 1 },
  { name: 'Humanitix',           tier: 1 },
  { name: 'SeatGeek',            tier: 1 },
  { name: 'Reddit r/sydney',     tier: 1 },
  { name: 'Yelp Events',         tier: 1 },
  { name: 'Google Places',       tier: 1 },
  { name: 'Skiddle',             tier: 1 },
  // Tier 2 — structured scraping
  { name: 'Resident Advisor',    tier: 2 },
  { name: 'Dice.fm',             tier: 2 },
  { name: 'TimeOut Sydney',      tier: 2 },
  { name: 'Broadsheet Sydney',   tier: 2 },
  { name: 'Concrete Playground', tier: 2 },
  { name: 'Sydney Opera House',  tier: 2 },
  { name: 'Art Gallery of NSW',  tier: 2 },
  { name: 'MCA Sydney',          tier: 2 },
  { name: 'City of Sydney',      tier: 2 },
  { name: 'Destination NSW',     tier: 2 },
  { name: 'Eventfinda',          tier: 2 },
  { name: 'TryBooking',          tier: 2 },
  { name: 'Moshtix',             tier: 2 },
  { name: 'Peatix',              tier: 2 },
  { name: 'WeTeachMe',           tier: 2 },
  { name: 'Carriageworks',       tier: 2 },
  { name: 'Seymour Centre',      tier: 2 },
  { name: 'The Music',           tier: 2 },
  { name: 'NSW Government',      tier: 2 },
  { name: 'Airbnb Experiences',  tier: 2 },
  { name: 'Ticketek',            tier: 2 },
  { name: 'Sydney Festival',     tier: 2 },
  { name: 'Mardi Gras',          tier: 2 },
  { name: 'SXSW Sydney',         tier: 2 },
  { name: 'Vivid Sydney',        tier: 2 },
  { name: 'Fuzzy Events',        tier: 2 },
  { name: 'Astral People',       tier: 2 },
  { name: 'Sweat It Out',        tier: 2 },
  { name: 'Goodgod Small Club',  tier: 2 },
  { name: 'Sydney Town Hall',    tier: 2 },
  { name: 'Enmore Theatre',      tier: 2 },
  { name: 'Metro Theatre',       tier: 2 },
  { name: 'Hordern Pavilion',    tier: 2 },
  { name: 'Factory Theatre',     tier: 2 },
  { name: 'Power Station',       tier: 2 },
  { name: 'Sydney Markets',      tier: 2 },
  { name: 'Secret Sounds',       tier: 2 },
  { name: 'Sydney Comedy Store', tier: 2 },
  { name: 'Powerhouse Museum',   tier: 2 },
];

module.exports = { SOURCES };
