// Lightweight source registry — names and tiers only, no fetch functions.
const SOURCES = [
  // ── Tier 1: API sources ──────────────────────────────────────────────────
  { name: 'Eventbrite',                  tier: 1 },
  { name: 'Meetup',                      tier: 1 },
  { name: 'Ticketmaster',                tier: 1 },
  { name: 'Songkick',                    tier: 1 },
  { name: 'Bandsintown',                 tier: 1 },
  { name: 'SeatGeek',                    tier: 1 },
  { name: 'Reddit r/sydney',             tier: 1 },
  { name: 'Yelp Events',                 tier: 1 },
  { name: 'Google Places',               tier: 1 },
  { name: 'Skiddle',                     tier: 1 },

  // ── Tier 2: Major listings platforms ────────────────────────────────────
  { name: 'Moshtix',                     tier: 2 },
  { name: 'Moshtix p2',                  tier: 2 },
  { name: 'Moshtix p3',                  tier: 2 },
  { name: 'Moshtix p4',                  tier: 2 },
  { name: 'Moshtix p5',                  tier: 2 },
  { name: 'Eventfinda',                  tier: 2 },
  { name: 'Eventfinda Sydney',           tier: 2 },
  { name: 'Eventbrite Sydney',           tier: 2 },
  { name: 'Humanitix',                   tier: 2 },
  { name: 'Humanitix Sydney',            tier: 2 },
  { name: 'TryBooking',                  tier: 2 },
  { name: 'TryBooking Sydney',           tier: 2 },
  { name: 'Peatix',                      tier: 2 },
  { name: 'Peatix Sydney',               tier: 2 },
  { name: 'OzTix',                       tier: 2 },
  { name: 'StickyTickets',               tier: 2 },
  { name: 'Ticketek',                    tier: 2 },
  { name: 'Ticketek Events',             tier: 2 },

  // ── Tier 2: Media & editorial ────────────────────────────────────────────
  { name: 'TimeOut Sydney',              tier: 2 },
  { name: 'TimeOut Sydney RSS',          tier: 2 },
  { name: 'TimeOut Food RSS',            tier: 2 },
  { name: 'Broadsheet Sydney',           tier: 2 },
  { name: 'Broadsheet RSS',              tier: 2 },
  { name: 'Concrete Playground',         tier: 2 },
  { name: 'Concrete Playground RSS',     tier: 2 },
  { name: 'Concrete Playground Events RSS', tier: 2 },
  { name: 'Happy Mag',                   tier: 2 },
  { name: 'Stoney Roads',                tier: 2 },
  { name: 'The Music',                   tier: 2 },
  { name: 'The Music RSS',               tier: 2 },
  { name: 'Music NSW',                   tier: 2 },
  { name: 'FBi Radio',                   tier: 2 },
  { name: 'Limelight Magazine',          tier: 2 },
  { name: 'Artshub',                     tier: 2 },
  { name: 'Daily Review',                tier: 2 },
  { name: 'Resident Advisor',            tier: 2 },

  // ── Tier 2: Government & tourism ────────────────────────────────────────
  { name: 'City of Sydney',              tier: 2 },
  { name: 'City of Sydney RSS',          tier: 2 },
  { name: 'Destination NSW',             tier: 2 },
  { name: 'Destination NSW Expanded',    tier: 2 },
  { name: 'NSW Government',              tier: 2 },
  { name: 'NSW Government Expanded',     tier: 2 },
  { name: 'Discover Parramatta',         tier: 2 },

  // ── Tier 3: Council events ───────────────────────────────────────────────
  { name: 'Waverley Council',            tier: 3 },
  { name: 'Waverley Council RSS',        tier: 3 },
  { name: 'Inner West Council',          tier: 3 },
  { name: 'Inner West RSS',              tier: 3 },
  { name: 'North Sydney Council',        tier: 3 },
  { name: 'Willoughby Council',          tier: 3 },
  { name: 'Randwick Council',            tier: 3 },
  { name: 'Northern Beaches Council',    tier: 3 },
  { name: 'City of Parramatta',          tier: 3 },
  { name: 'Bayside Council',             tier: 3 },
  { name: 'Sutherland Shire',            tier: 3 },
  { name: 'Ku-ring-gai Council',         tier: 3 },

  // ── Tier 2: Performing arts ──────────────────────────────────────────────
  { name: 'Sydney Opera House',          tier: 2 },
  { name: 'Sydney Opera House Expanded', tier: 2 },
  { name: 'Seymour Centre',              tier: 2 },
  { name: 'Carriageworks',               tier: 2 },
  { name: 'Belvoir St Theatre',          tier: 2 },
  { name: 'Sydney Theatre Company',      tier: 2 },
  { name: 'Griffin Theatre',             tier: 2 },
  { name: 'Ensemble Theatre',            tier: 2 },
  { name: 'Hayes Theatre',               tier: 2 },
  { name: 'State Theatre',               tier: 2 },
  { name: 'Old Fitzroy Theatre',         tier: 2 },
  { name: 'Bangarra Dance Theatre',      tier: 2 },
  { name: 'Sydney Symphony Orchestra',   tier: 2 },
  { name: 'Australian Chamber Orchestra',tier: 2 },
  { name: 'Monkey Baa Theatre',          tier: 2 },
  { name: 'The Concourse',               tier: 2 },
  { name: 'Factory Theatre',             tier: 2 },
  { name: 'Sydney Town Hall',            tier: 2 },

  // ── Tier 2: Music venues ──────────────────────────────────────────────────
  { name: 'Dice.fm',                     tier: 2 },
  { name: 'Dice FM Sydney',              tier: 2 },
  { name: 'Oxford Art Factory',          tier: 2 },
  { name: 'Enmore Theatre',              tier: 2 },
  { name: 'Enmore Theatre Direct',       tier: 2 },
  { name: 'Metro Theatre',               tier: 2 },
  { name: 'Metro Direct',                tier: 2 },
  { name: 'Hordern Pavilion',            tier: 2 },
  { name: 'Hordern Direct',              tier: 2 },
  { name: 'Power Station',               tier: 2 },
  { name: 'Goodgod Direct',              tier: 2 },
  { name: 'Sweat It Out',                tier: 2 },
  { name: 'Sweat It Out Direct',         tier: 2 },
  { name: 'Secret Sounds',               tier: 2 },
  { name: 'Secret Sounds Direct',        tier: 2 },
  { name: 'Fuzzy Events',                tier: 2 },
  { name: 'Astral People',               tier: 2 },
  { name: 'Manning Bar',                 tier: 2 },
  { name: 'Bald Faced Stag',             tier: 2 },
  { name: 'Marrickville Bowlo',          tier: 2 },
  { name: 'The Vanguard',                tier: 2 },
  { name: 'Old 505',                     tier: 2 },
  { name: 'Imperial Hotel',              tier: 2 },
  { name: 'Sofar Sounds',                tier: 2 },

  // ── Tier 2: Museums & galleries ──────────────────────────────────────────
  { name: 'Art Gallery of NSW',          tier: 2 },
  { name: 'MCA Sydney',                  tier: 2 },
  { name: 'MCA Expanded',                tier: 2 },
  { name: 'Powerhouse Museum',           tier: 2 },
  { name: 'Australian Museum',           tier: 2 },
  { name: 'Sydney Living Museums',       tier: 2 },
  { name: 'Taronga Zoo',                 tier: 2 },
  { name: 'State Library NSW',           tier: 2 },
  { name: 'White Rabbit Gallery',        tier: 2 },
  { name: 'Campbelltown Arts Centre',    tier: 2 },
  { name: 'Casula Powerhouse',           tier: 2 },
  { name: 'Hazelhurst Arts Centre',      tier: 2 },
  { name: 'Penrith Regional Gallery',    tier: 2 },
  { name: '4A Contemporary Asian Art',   tier: 2 },

  // ── Tier 3: Markets ──────────────────────────────────────────────────────
  { name: 'Sydney Markets',              tier: 3 },
  { name: 'Marrickville Organic Market', tier: 3 },
  { name: 'Kirribilli Markets',          tier: 3 },
  { name: 'Balmain Market',              tier: 3 },
  { name: 'Manly Markets',               tier: 3 },
  { name: 'Eveleigh Market',             tier: 3 },
  { name: 'Rozelle Markets',             tier: 3 },
  { name: 'Orange Grove Market',         tier: 3 },

  // ── Tier 2: Festivals ────────────────────────────────────────────────────
  { name: 'Sydney Film Festival',        tier: 2 },
  { name: 'Sydney Comedy Festival',      tier: 2 },
  { name: 'Sydney Fringe',               tier: 2 },
  { name: 'Sculpture by the Sea',        tier: 2 },
  { name: 'Night Noodle Markets',        tier: 2 },
  { name: 'Roar and Snore',              tier: 2 },
  { name: 'Laneway Festival',            tier: 2 },
  { name: 'Sydney Festival',             tier: 2 },
  { name: 'Mardi Gras',                  tier: 2 },
  { name: 'SXSW Sydney',                 tier: 2 },
  { name: 'Vivid Sydney',                tier: 2 },

  // ── Tier 3: Sport ────────────────────────────────────────────────────────
  { name: 'City2Surf',                   tier: 3 },
  { name: 'Sydney Running Festival',     tier: 3 },

  // ── Tier 3: Other ────────────────────────────────────────────────────────
  { name: 'WeTeachMe',                   tier: 3 },
  { name: 'WeTeachMe Expanded',          tier: 3 },
  { name: 'Airbnb Experiences',          tier: 3 },
  { name: 'Airbnb Experiences Sydney',   tier: 3 },
  { name: 'Sydney Comedy Store',         tier: 2 },
];

module.exports = { SOURCES };
